#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

case $1 in
  start)
    # The '| cat' is to trick Node that this is an non-TTY terminal
    # then react-scripts won't clear the console.
    yarn start | cat
    ;;
  build)
    yarn build
    touch ${BUILD_COMPLETE_FILE}
    chmod 777 ${BUILD_COMPLETE_FILE}
    ;;
  test)
    yarn test $@
    ;;
  *)
    exec "$@"
    ;;
esac

