#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

case $1 in
  start)
    # The '| cat' is to trick Node that this is an non-TTY terminal
    # then react-scripts won't clear the console.
    npm run start | cat
    ;;
  build)
    chmod a+w $(dirname ${BUILD_COMPLETE_FILE})
    npm run build
    touch ${BUILD_COMPLETE_FILE}
    ;;
  test)
    npm test $@
    ;;
  *)
    exec "$@"
    ;;
esac

